
package ws;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PasswordManagerWSImplService", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:8080/WS/PasswordManager?wsdl")
public class PasswordManagerWSImplService
    extends Service
{

    private final static URL PASSWORDMANAGERWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PASSWORDMANAGERWSIMPLSERVICE_EXCEPTION;
    private final static QName PASSWORDMANAGERWSIMPLSERVICE_QNAME = new QName("http://ws/", "PasswordManagerWSImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WS/PasswordManager?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PASSWORDMANAGERWSIMPLSERVICE_WSDL_LOCATION = url;
        PASSWORDMANAGERWSIMPLSERVICE_EXCEPTION = e;
    }

    public PasswordManagerWSImplService() {
        super(__getWsdlLocation(), PASSWORDMANAGERWSIMPLSERVICE_QNAME);
    }

    public PasswordManagerWSImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PASSWORDMANAGERWSIMPLSERVICE_QNAME, features);
    }

    public PasswordManagerWSImplService(URL wsdlLocation) {
        super(wsdlLocation, PASSWORDMANAGERWSIMPLSERVICE_QNAME);
    }

    public PasswordManagerWSImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PASSWORDMANAGERWSIMPLSERVICE_QNAME, features);
    }

    public PasswordManagerWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PasswordManagerWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PasswordManagerWS
     */
    @WebEndpoint(name = "PasswordManagerWSImplPort")
    public PasswordManagerWS getPasswordManagerWSImplPort() {
        return super.getPort(new QName("http://ws/", "PasswordManagerWSImplPort"), PasswordManagerWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PasswordManagerWS
     */
    @WebEndpoint(name = "PasswordManagerWSImplPort")
    public PasswordManagerWS getPasswordManagerWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "PasswordManagerWSImplPort"), PasswordManagerWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PASSWORDMANAGERWSIMPLSERVICE_EXCEPTION!= null) {
            throw PASSWORDMANAGERWSIMPLSERVICE_EXCEPTION;
        }
        return PASSWORDMANAGERWSIMPLSERVICE_WSDL_LOCATION;
    }

}
